import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import process from "process";

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository (https://github.com/phibr0/obsidian-dictionary)
*/
`;

const ctx = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: ['obsidian'],
    format: 'cjs',
    minify: true,
    logLevel: "info",
    plugins: [sveltePlugin({
        compileOptions: {
            css: true,
            dev: true,
        },
    })],
    outfile: 'main.js',
});

await ctx.watch();
console.log('Watching for changes...');