import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import process from "process";

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository (https://github.com/ashleyjackson/obsidian-charts)
*/
`;

esbuild.build({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: ['obsidian', 'moment'],
    format: 'cjs',
    minify: true,
    logLevel: "info",
    treeShaking: true,
    plugins: [sveltePlugin({
        compileOptions: {
            css: true,
            dev: false,
        },
    })],
    outfile: 'main.js',
}).catch(() => process.exit(1));